spring:
  application:
    name: lmsServerApplication
  datasource:
    url: jdbc://192.168.138.133:3306//business_lms
mybatis:
  mapper-locations: classpath:mapper/*.xml;
  configuration:
    map-underscore-to-camel-case: true